### PR TITLE
Fix 148

### LINKED ISSUE #148: golang.org: Couldn't determine upstream package name
```
$ dh-make-golang make -type lib golang.org/x/term
2020/12/10 10:54:25 Starting "dh-make-golang v0.4.0 linux/amd64"
2020/12/10 10:54:25 Downloading "golang.org/x/term/..."
2020/12/10 10:54:26 Determining upstream version number
2020/12/10 10:54:26 Package version is "0.0~git20201207.ee85cb9"
2020/12/10 10:54:26 Determining dependencies
2020/12/10 10:54:27 Generating temp tarball as "/tmp/dh-make-golang912173610"
2020/12/10 10:54:27 Moving tempfile to "golang-golang-TODO-term_0.0~git20201207.ee85cb9.orig.tar.xz"
2020/12/10 10:54:27 Adding remote "origin" with URL "git@salsa.debian.org:go-team/packages/golang-golang-TODO-term.git"
2020/12/10 10:54:27 Adding remote "golang" with URL "https://go.googlesource.com/term"
2020/12/10 10:54:27 Running "git fetch golang"
remote: Total 280 (delta 159), reused 280 (delta 159)
Receiving objects: 100% (280/280), 86.14 KiB | 1.03 MiB/s, done.
Resolving deltas: 100% (159/159), done.
From https://go.googlesource.com/term
 * [new branch]      master                  -> golang/master
 * [new branch]      tmp.crypto-ssh-terminal -> golang/tmp.crypto-ssh-terminal
gbp:error: Couldn't determine upstream package name. Use --interactive.
2020/12/10 10:54:28 Could not create git repository: exit status 1
```

Any idea?

### PR DESCRIPTION
**Pull request by elboulangero**
Closes #148 I believe.

~~I could not test yet as I struggle to `go install` dh-make-golang...~~

Tested, it works.

### CODE REVIEW

**Review by zhsj — CHANGES_REQUESTED** [review]
Could you add tests in

https://github.com/Debian/dh-make-golang/blob/3671570fd0c4668c64abf941d58a9c8adfe6b396/make_test.go#L47-L55

as well as the case in #127 like `git.sr.ht/~sircmpwn/getopt`

**Comment by elboulangero** [comment]
Thanks for pointing that out, just pushed an update with more test cases.

I expected that the test with `git.sr.ht/~sircmpwn/getopt` would fail due to the tilde being transformed in a dash, but no. What actually happens is that `normalizeDebianProgramName()` simply drops the tilde.

**Review by zhsj — APPROVED** [review]

**Comment by zhsj** [comment]
lint failed, as the file is not `gofmt`.

**Comment by elboulangero** [comment]
> lint failed, as the file is not gofmt.

Oh I see, I just fixed it. I just spent 10 minutes trying to understand why gofmt sometimes formats string concatenation as `"a"+"b"` and sometimes `"a" + "b"`, and really, I don't understand. But anyway.

**Pull request merged**
